language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy"
    - "pypy3"
jobs:
  include:
    - python: 3.7
      os: linux
    - python: 3.8
      os: linux

install:
    - make init
script:
    make test
